import Footer from "@/components/miso/Footer";
import HeaderFinal from "@/components/miso/HeaderFinal";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RedButton",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ margin: "0 " }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderFinal />
        {children}
        <Footer />
      </body>
    </html>
  );
}
