import Footer from "@/components/miso/Footer";
import Game from "@/components/miso/Game";
import Header from "@/components/miso/Header";
import HeaderFinal from "@/components/miso/HeaderFinal";
import HeaderMenu from "@/components/miso/HeaderMenu";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RedButton",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //헤더 푸터
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderFinal></HeaderFinal>
        <Game></Game>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
